feat(Climbing): set default speed of 0.0 when updating dashboard sensors
```bash
[629.26] Error at /home/lvuser/py/subsystems/climbing.py.32:__init__: Unhandled exception
[629.26]
[629.26] Traceback (most recent call last):
[629.26]   File "/usr/local/lib/python3.8/site-packages/wpilib/_impl/start.py", line 106, in start
[629.26]     self.robot.startCompetition()
[629.26]   File "/home/lvuser/py/robot.py", line 40, in robotInit
[629.27]     self.climbing = Climbing(self)
[629.27]   File "/home/lvuser/py/subsystems/climbing.py", line 32, in __init__
[629.27]     self._update_smartdashboard_sensors()
[629.27]   File "/usr/local/lib/python3.8/site-packages/wpilib/_impl/start.py", line 106, in start
[629.27]     self.robot.startCompetition()
[629.27]   File "/home/lvuser/py/robot.py", line 40, in robotInit
[629.27]     self.climbing = Climbing(self)
[629.27]   File "/home/lvuser/py/subsystems/climbing.py", line 32, in __init__
[629.27]     self._update_smartdashboard_sensors()
[629.27] TypeError: _update_smartdashboard_sensors() missing 1 required positional argument: 'speed'
[629.27]
```