ci(travis): remove python version 3.6 build add gcc 7 for compilation
Travis fails with pip wheel compilation failure. This attempts to fix
that.

```bash
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -DRPYBUILD_MODULE_NAME=_wpiutil -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/include -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/rpy-include -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/src/type_casters -I/tmp/pip-build-env-a8wwqkr_/overlay/lib/python3.8/site-packages/robotpy_build/pybind11/include -I/tmp/pip-build-env-a8wwqkr_/overlay/lib/python3.8/site-packages/robotpy_build/include -Ibuild/temp.linux-x86_64-3.8/gensrc/wpiutil -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil -I/opt/python/3.8.0/include/python3.8 -c wpiutil/src/main.cpp -o build/temp.linux-x86_64-3.8/wpiutil/src/main.o -s -g0 -std=c++17 -fvisibility=hidden
        gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -DRPYBUILD_MODULE_NAME=_wpiutil -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/include -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/rpy-include -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/src/type_casters -I/tmp/pip-build-env-a8wwqkr_/overlay/lib/python3.8/site-packages/robotpy_build/pybind11/include -I/tmp/pip-build-env-a8wwqkr_/overlay/lib/python3.8/site-packages/robotpy_build/include -Ibuild/temp.linux-x86_64-3.8/gensrc/wpiutil -I/tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil -I/opt/python/3.8.0/include/python3.8 -c build/temp.linux-x86_64-3.8/gensrc/wpiutil/PortForwarder.cpp -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/gensrc/wpiutil/PortForwarder.o -s -g0 -std=c++17 -fvisibility=hidden
        In file included from /tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/include/wpi/StringRef.h:13:0,
                         from /tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/include/wpi/Twine.h:14,
                         from /tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/include/wpi/PortForwarder.h:15,
                         from build/temp.linux-x86_64-3.8/gensrc/wpiutil/PortForwarder.cpp:5:
        /tmp/pip-install-stx9499h/robotpy-wpiutil/wpiutil/include/wpi/STLExtras.h:34:20: fatal error: optional: No such file or directory
        compilation terminated.
        error: command 'gcc' failed with exit status 1
        ----------------------------------------
        ERROR: Failed building wheel for robotpy-wpiutil
        Running setup.py clean for robotpy-wpiutil
      Failed to build robotpy-wpiutil
      ERROR: Could not build wheels for robotpy-wpiutil which use PEP 517 and cannot be installed directly
      ----------------------------------------
    ERROR: Command errored out with exit status 1: /home/travis/build/TechnoJays/robot2020/.tox/py38/bin/python /home/travis/build/TechnoJays/robot2020/.tox/py38/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_zny8fvi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'robotpy-build>=2020.0.17,<2021.0.0' 'robotpy-wpiutil>=2020.1.2.2,<2021.0.0' Check the logs for full command output.
    ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/travis/build/TechnoJays/robot2020/.tox/py38/bin/python /home/travis/build/TechnoJays/robot2020/.tox/py38/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-1nbyh7sg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'robotpy-build>=2020.0.18,<2021.0.0' 'robotpy-wpiutil>=2020.1.2.2,<2021.0.0' 'robotpy-hal>=2020.1.2.2,<2021.0.0' 'pyntcore>=2020.1.2.1,<2021.0.0' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/travis/build/TechnoJays/robot2020/.tox/py38/bin/python /home/travis/build/TechnoJays/robot2020/.tox/py38/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gdprx_g9/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'robotpy-build>=2020.0.19,<2021.0.0' 'wpilib>=2020.1.2.3,<2021.0.0' Check the logs for full command output.
=================================== log end ====================================
___________________________________ summary ____________________________________
ERROR:   py38: InvocationError for command /home/travis/build/TechnoJays/robot2020/.tox/py38/bin/python -m pip install --exists-action w .tox/.tmp/package/1/team94_robot_2020-0.0.1.zip (exited with code 1)
The command "tox" exited with 1.
```